package app.Client.Layers.BlockchainLayer;

public enum ValidationStatus {
    VALID,
    INVALID,
    NEED_PREDECESSOR,
    LOSING_FORK,
    LOSING_FORK_LOSES_SECONDARY_CHECK,
    EQUAL_FORK,
    LOSES_PRIMARY_CHECK,
    LOSES_SECONDARY_CHECK,
    EXISTING_CHAIN_REQUEST,
    NEED_PREDECESSOR_LOSING_FORK,
    NEED_PREDECESSOR_EQUAL_FORK
}
